package com.audiorelay.app.network

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Test

class CryptoTest {

    @Test
    fun `same inputs derive the same key`() {
        val k1 = Crypto.deriveSessionKey("042817", "phone-1", "laptop-1")
        val k2 = Crypto.deriveSessionKey("042817", "phone-1", "laptop-1")
        assertArrayEquals(k1, k2)
    }

    @Test
    fun `different code derives a different key`() {
        val k1 = Crypto.deriveSessionKey("042817", "phone-1", "laptop-1")
        val k2 = Crypto.deriveSessionKey("999999", "phone-1", "laptop-1")
        assert(!k1.contentEquals(k2))
    }

    @Test
    fun `repair proof round trips`() {
        val key = Crypto.deriveSessionKey("042817", "phone-1", "laptop-1")
        val proof = Crypto.computeRepairProof(key, "phone-1", "some-nonce")
        val expected = Crypto.computeRepairProof(key, "phone-1", "some-nonce")
        assertEquals(expected, proof)
    }

    @Test
    fun `pair proof round trips`() {
        val proof = Crypto.computePairProof("042817", "phone-1", "some-nonce")
        val expected = Crypto.computePairProof("042817", "phone-1", "some-nonce")
        assertEquals(expected, proof)
    }

    @Test
    fun `pair proof rejects wrong code`() {
        val proof = Crypto.computePairProof("042817", "phone-1", "some-nonce")
        val other = Crypto.computePairProof("999999", "phone-1", "some-nonce")
        assert(proof != other)
    }

    @Test
    fun `pair proof rejects wrong nonce`() {
        val proof = Crypto.computePairProof("042817", "phone-1", "some-nonce")
        val other = Crypto.computePairProof("042817", "phone-1", "other-nonce")
        assert(proof != other)
    }

    @Test
    fun `pair proof does not leak the code itself`() {
        val proof = Crypto.computePairProof("042817", "phone-1", "some-nonce")
        assert(!proof.contains("042817"))
    }

    @Test
    fun `hex round trips`() {
        val bytes = byteArrayOf(0xDE.toByte(), 0xAD.toByte(), 0xBE.toByte(), 0xEF.toByte())
        val hex = Crypto.toHex(bytes)
        assertEquals("deadbeef", hex)
        assertArrayEquals(bytes, Crypto.hexToBytes(hex))
    }

    @Test
    fun `decrypt throws on tampered ciphertext`() {
        val key = Crypto.deriveSessionKey("042817", "phone-1", "laptop-1")
        val sessionId = ByteArray(8) { it.toByte() }
        val header = ByteArray(13)
        val cipher = javax.crypto.Cipher.getInstance("ChaCha20-Poly1305")
        // Encrypt via the same low-level primitive Crypto.decryptPayload uses,
        // just in ENCRYPT_MODE — Crypto itself is decrypt-only (this app is a
        // receiver), see the comment on decryptPayload.
        val nonce = ByteArray(12).also {
            sessionId.copyInto(it, 0)
            it[8] = 0; it[9] = 0; it[10] = 0; it[11] = 7
        }
        cipher.init(
            javax.crypto.Cipher.ENCRYPT_MODE,
            javax.crypto.spec.SecretKeySpec(key, "ChaCha20"),
            javax.crypto.spec.IvParameterSpec(nonce),
        )
        cipher.updateAAD(header)
        val ciphertext = cipher.doFinal("hello".toByteArray())
        ciphertext[ciphertext.size - 1] = (ciphertext[ciphertext.size - 1].toInt() xor 0xFF).toByte()

        assertThrows(Crypto.AeadException::class.java) {
            Crypto.decryptPayload(key, sessionId, 7u, header, ciphertext)
        }
    }

    /**
     * Cross-implementation check: this exact key/session_id/header/plaintext
     * and its resulting ciphertext were generated by
     * `desktop-app/src/protocol/crypto.rs`'s
     * `vector_gen::print_known_answer_vector` test (also asserted as a
     * regression there in `known_vector_matches_android_side`). Decrypting
     * it here and recovering the same plaintext is the strongest evidence
     * this repo has that the two independent AEAD implementations
     * (Rust `chacha20poly1305` crate vs. Android's `Cipher.getInstance("ChaCha20-Poly1305")`)
     * actually agree on the wire format — not just each internally
     * consistent.
     */
    @Test
    fun `decryptPayload matches the desktop-app reference vector`() {
        val key = Crypto.hexToBytes("f1056de4e89aa1c938953775624a38a79f961023e9d9955cafcdd2efdc4e67c2")
        val sessionId = Crypto.hexToBytes("3132333435363738")
        val header = Crypto.hexToBytes("00000000070000003e08010200")
        val ciphertext = Crypto.hexToBytes(
            "0094c8034b5be30d97accae01a756b29359ae4759e7324aefc36d8968afbfa9242456b11fc40982feac08aa91dc17d07",
        )

        val plaintext = Crypto.decryptPayload(key, sessionId, 7u, header, ciphertext)

        assertEquals("cross-implementation test vector", String(plaintext, Charsets.UTF_8))
    }
}
